export const ADD_PRODUCT_BASKET = 'ADD_PRODUCT_BASKET'
export const GET_NUMBERS_BASKET = 'GET_NUMBERS_BASKET'
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY'
export const DESCREASE_QUANTITY = 'DESCREASE_QUANTITY'
export const REMOVE_ITEM = "REMOVE_ITEM"